# Generated by Django 3.2.9 on 2021-11-19 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='название типа счёта')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='название счёта')),
                ('summ', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='сумма счёта')),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountapp.accounttype', verbose_name='тип счёта')),
            ],
        ),
    ]
