# Generated by Django 3.2.9 on 2021-11-26 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogapp', '0003_counterparties_description'),
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='стоимость операции')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
                ('data', models.DateField(verbose_name='Дата операции')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountapp.account', verbose_name='счёт')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogapp.category', verbose_name='категория операции')),
                ('category_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogapp.categoryunit', verbose_name='название операции')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogapp.counterparties', verbose_name='контрагент')),
            ],
        ),
    ]
